config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :rounds
  resources :bets
end

app/models/round.rb
class Round < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 15 }
  validates :hole1_score, presence: true, numericality: { only_integer: true }
  validates :hole2_score, presence: true, numericality: { only_integer: true }
  validates :hole3_score, presence: true, numericality: { only_integer: true }
  validates :hole4_score, presence: true, numericality: { only_integer: true }
  validates :hole5_score, presence: true, numericality: { only_integer: true }
  validates :hole6_score, presence: true, numericality: { only_integer: true }
  validates :hole7_score, presence: true, numericality: { only_integer: true }
  validates :hole8_score, presence: true, numericality: { only_integer: true }
  validates :hole9_score, presence: true, numericality: { only_integer: true }
  validates :hole10_score, presence: true, numericality: { only_integer: true }
  validates :hole11_score, presence: true, numericality: { only_integer: true }
  validates :hole12_score, presence: true, numericality: { only_integer: true }
  validates :hole13_score, presence: true, numericality: { only_integer: true }
  validates :hole14_score, presence: true, numericality: { only_integer: true }
  validates :hole15_score, presence: true, numericality: { only_integer: true }
  validates :hole16_score, presence: true, numericality: { only_integer: true }
  validates :hole17_score, presence: true, numericality: { only_integer: true }
  validates :hole18_score, presence: true, numericality: { only_integer: true }
  default_scope -> { order(created_at: :desc) }
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  
  def index
    @rounds = Round.where("created_at >= ?", Time.zone.now.beginning_of_day)
    
  end
  
  def new
    @round = Round.new
  end
  
  def create
    @round = Round.new(round_params)
    if @round.save
      redirect_to rounds_url
    else
      flash[:danger] = "Hey Mel, Don't Forget Your Name!"
      redirect_to new_round_path
    end
  end
  
  def edit
    @round = Round.find(params[:id])
  end
  
  def update
    @round = Round.find(params[:id])
    if @round.update_attributes(round_params)
      flash[:success] = "Round updated"
      redirect_to rounds_path
    else
      render 'edit'
    end
  end
  
  private
    def round_params
      params.require(:round).permit(:name, :hole1_score, :hole2_score, :hole3_score, :hole4_score, :hole5_score, :hole6_score,
                                    :hole7_score, :hole8_score, :hole9_score, :hole10_score, :hole11_score, :hole12_score,
                                    :hole13_score, :hole14_score, :hole15_score, :hole16_score, :hole17_score, :hole18_score)
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
  
  def style_hole(score, hole) 
   pars = [5, 4, 3, 3, 4, 4, 4, 4, 5, 4, 4, 4, 3, 3, 5, 4, 4, 5] 
     if score.to_i - pars[hole] == -1 
       "birdie" 
     elsif score.to_i - pars[hole] == 1 
       "bogey"
      elsif score.to_i - pars[hole] > 1 
       "other"
     end 
  end
end

app/views/rounds/edit.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <h1>Edit a Round</h1>
    <%= form_for @round do |f| %>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control round-form' %>
      </p>
      <% 18.times do |n| %>
        <p>
          <%= f.label :"hole#{n+1}_score", "Hole #{n+1}" %><br>
          <%= submit_tag "-", type: 'button', onClick: %{decrementValue("hole#{n+1}")},
                              class: "stepper-btns btn btn-lg btn-success" %>
          <%= f.text_field :"hole#{n+1}_score",
                              class: 'form-control round-form',
                              id: "hole#{n+1}" %>
           <%= submit_tag "+", type: 'button', onClick: %{incrementValue("hole#{n+1}")},
                               class: "stepper-btns btn btn-lg btn-success", id: "plus" %>
      <% end %>
      <p>
        <%= f.submit "Submit", class: 'btn btn-primary btn-lg' %>
      </p>
    <% end %> 
  </div>
</div>

app/views/rounds/index.html.erb
<% par = [5,4,3,3,4,4,4,4,5,4,4,4,3,3,5,4,4,5] %>

<h1>All Rounds</h1>
<div><%= link_to "Add Round", new_round_path, class: "btn btn-success" %></div>
<br>
<small>(Click Player Name to Edit)</small>

<table class='table table-striped table-bordered' id='rounds-table'>
  <thead>
    <tr>
      <th class='fixed-col'>HOLE</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
      <th>6</th>
      <th>7</th>
      <th>8</th>
      <th>9</th>
      <th>F9</th>
      <th>10</th>
      <th>11</th>
      <th>12</th>
      <th>13</th>
      <th>14</th>
      <th>15</th>
      <th>16</th>
      <th>17</th>
      <th>18</th>
      <th>B9</th>
      <th>TL</th>
    </tr>
    <tr id='par-row'>
      <th class='fixed-col'>PAR</th>
      <th>5</th>
      <th>4</th>
      <th>3</th>
      <th>3</th>
      <th>4</th>
      <th>4</th>
      <th>4</th>
      <th>4</th>
      <th>5</th>
      <th>36</th>
      <th>4</th>
      <th>4</th>
      <th>4</th>
      <th>3</th>
      <th>3</th>
      <th>5</th>
      <th>4</th>
      <th>4</th>
      <th>5</th>
      <th>36</th>
      <th>72</th>
    </tr>
  </thead>

<% @rounds.each do |round| %>
  <tr>
    <td class='fixed-col'><%= link_to round.name, edit_round_path(round) %></td> 
    <% 9.times do |n| %>
      <td class=<%= style_hole(round["hole#{n+1}_score"], n) %>>
        <%= round["hole#{n+1}_score"] %>
      </td>
    <% end %>
    
    <!--#front 9 total tbd-->
    <% front = [] %>
    <% 9.times do |n| %> 
      <% front << round["hole#{n+1}_score"].to_i %>
    <% end %>
    <td><%= front.reduce(:+).to_s %></td>
    
    <% 9.times do |n| %>
      <td class=<%= style_hole(round["hole#{n+10}_score"], n+9) %>>
        <%= round["hole#{n+10}_score"] %>
      </td>
    <% end %>
    
    <!--#back 9 total tbd-->
    <% back = [] %>
    <% 9.times do |n| %> 
      <% back << round["hole#{n+10}_score"].to_i %>
    <% end %>
    <td><%= back.reduce(:+).to_s %></td>
    
    <!--18 hole total tbd-->
    <td><%= (front.reduce(:+) + back.reduce(:+)).to_s  %></td> 
  </tr>
<% end %>

app/views/rounds/new.html.erb
<% par = [5,4,3,3,4,4,4,4,5,4,4,4,3,3,5,4,4,5] %>

<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <h1>Enter a New Round</h1>
    <%= form_for @round do |f| %>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control round-form' %>
      </p>
      <% 18.times do |n| %>
        <p>
          <%= f.label :"hole#{n+1}_score", "Hole #{n+1}" %><br>
          <%= submit_tag "-", type: 'button', onClick: %{decrementValue("hole#{n+1}")},
                              class: "stepper-btns btn btn-lg btn-success" %>
          <%= f.text_field :"hole#{n+1}_score", value: "#{par[n]}",
                              class: 'form-control round-form',
                              id: "hole#{n+1}" %>
           <%= submit_tag "+", type: 'button', onClick: %{incrementValue("hole#{n+1}")},
                               class: "stepper-btns btn btn-lg btn-success", id: "plus" %>
      <% end %>
      <p>
        <%= f.submit "Submit", class: 'btn btn-primary btn-lg' %>
      </p>
    <% end %> 
  </div>
</div>

<!--practice for stepper buttons-->
<!--<div class="input-stepper">-->
<!--  <button onClick = "decrementValue('x')">-</button>-->
<!--	<input id="x" type="text" value="6" >-->
<!--	<button onClick = "incrementValue('x')">+</button>-->
<!--</div>-->