config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :rounds
  resources :bets
end

app/views/layouts/_header.html.erb
<header class = 'navbar navbar-inverse'>
  <div class='container-fluid'>
    <div class='navbar-header pull-left'>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
              data-target="#navbar-collapse-1" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>  
    </div>
    
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class='nav navbar-nav'>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "New Round", new_round_path %></li>
        <li><%= link_to "All Rounds", rounds_path %></li>
        <li><%= link_to "New Bet", new_bet_path %></li>
        <li><%= link_to "All Bets", bets_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GolfBetApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <% flash.each do |message_type, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{message_type}") %>  
      <% end %>
      <%= yield %>
    <!--<%= debug(params) if Rails.env.development? %>-->
    </div>
   
  </body>
</html>